#pragma once

/* Amalgamated include. Generated automatically during Gkeyll "make install" */

#ifdef __cplusplus
extern "C" {
#endif

#include <gkyl_alloc.h>
#include <gkyl_ambi_bolt_potential.h>
#include <gkyl_array.h>
#include <gkyl_array_integrate.h>
#include <gkyl_array_ops.h>
#include <gkyl_array_reduce.h>
#include <gkyl_array_rio.h>
#include <gkyl_array_rio_format_desc.h>
#include <gkyl_basis.h>
#include <gkyl_bc_basic.h>
#include <gkyl_bc_emission_spectrum.h>
#include <gkyl_bc_sheath_gyrokinetic.h>
#include <gkyl_bc_twistshift.h>
#include <gkyl_bgk_collisions.h>
#include <gkyl_block_topo.h>
#include <gkyl_comm.h>
#include <gkyl_const.h>
#include <gkyl_correct_maxwellian_gyrokinetic.h>
#include <gkyl_cusolver_ops.h>
#include <gkyl_dflt.h>
#include <gkyl_dg_advection.h>
#include <gkyl_dg_basis_ops.h>
#include <gkyl_dg_bin_ops.h>
#include <gkyl_dg_calc_canonical_pb_vars.h>
#include <gkyl_dg_calc_em_vars.h>
#include <gkyl_dg_calc_fluid_em_coupling.h>
#include <gkyl_dg_calc_fluid_vars.h>
#include <gkyl_dg_calc_pkpm_dist_vars.h>
#include <gkyl_dg_calc_pkpm_em_coupling.h>
#include <gkyl_dg_calc_pkpm_vars.h>
#include <gkyl_dg_calc_prim_vars.h>
#include <gkyl_dg_calc_sr_vars.h>
#include <gkyl_dg_canonical_pb.h>
#include <gkyl_dg_cx.h>
#include <gkyl_dg_diffusion_fluid.h>
#include <gkyl_dg_diffusion_gen.h>
#include <gkyl_dg_diffusion_gyrokinetic.h>
#include <gkyl_dg_diffusion_vlasov.h>
#include <gkyl_dg_eqn.h>
#include <gkyl_dg_euler.h>
#include <gkyl_dg_euler_pkpm.h>
#include <gkyl_dg_fpo_vlasov_diff.h>
#include <gkyl_dg_fpo_vlasov_drag.h>
#include <gkyl_dg_gyrokinetic.h>
#include <gkyl_dg_iz.h>
#include <gkyl_dg_lbo_gyrokinetic_diff.h>
#include <gkyl_dg_lbo_gyrokinetic_drag.h>
#include <gkyl_dg_lbo_pkpm_diff.h>
#include <gkyl_dg_lbo_pkpm_drag.h>
#include <gkyl_dg_lbo_vlasov_diff.h>
#include <gkyl_dg_lbo_vlasov_drag.h>
#include <gkyl_dg_maxwell.h>
#include <gkyl_dg_prim_vars_gyrokinetic.h>
#include <gkyl_dg_prim_vars_transform_vlasov_gk.h>
#include <gkyl_dg_prim_vars_type.h>
#include <gkyl_dg_prim_vars_vlasov.h>
#include <gkyl_dg_updater_bflux_gyrokinetic.h>
#include <gkyl_dg_updater_bflux_vlasov.h>
#include <gkyl_dg_updater_diffusion_fluid.h>
#include <gkyl_dg_updater_diffusion_gen.h>
#include <gkyl_dg_updater_diffusion_gyrokinetic.h>
#include <gkyl_dg_updater_diffusion_vlasov.h>
#include <gkyl_dg_updater_fluid.h>
#include <gkyl_dg_updater_fpo_vlasov.h>
#include <gkyl_dg_updater_gyrokinetic.h>
#include <gkyl_dg_updater_lbo_gyrokinetic.h>
#include <gkyl_dg_updater_lbo_pkpm.h>
#include <gkyl_dg_updater_lbo_vlasov.h>
#include <gkyl_dg_updater_moment.h>
#include <gkyl_dg_updater_moment_pkpm.h>
#include <gkyl_dg_updater_pkpm.h>
#include <gkyl_dg_updater_rad_vlasov.h>
#include <gkyl_dg_updater_vlasov.h>
#include <gkyl_dg_vlasov.h>
#include <gkyl_dg_vlasov_alpha_gen_geo.h>
#include <gkyl_dg_vlasov_pkpm.h>
#include <gkyl_dg_vlasov_sr.h>
#include <gkyl_dual_num.h>
#include <gkyl_dynvec.h>
#include <gkyl_elem_type.h>
#include <gkyl_eqn_type.h>
#include <gkyl_eval_offset_fd.h>
#include <gkyl_eval_on_nodes.h>
#include <gkyl_evalf_def.h>
#include <gkyl_fem_parproj.h>
#include <gkyl_fem_poisson.h>
#include <gkyl_fem_poisson_bctype.h>
#include <gkyl_fem_poisson_perp.h>
#include <gkyl_fv_proj.h>
#include <gkyl_gauss_quad_data.h>
#include <gkyl_ghost_surf_calc.h>
#include <gkyl_gkgeom.h>
#include <gkyl_gr_blackhole.h>
#include <gkyl_gr_minkowski.h>
#include <gkyl_gr_spacetime.h>
#include <gkyl_gr_spacetime_diff.h>
#include <gkyl_hyper_dg.h>
#include <gkyl_job_pool.h>
#include <gkyl_kep_scheme.h>
#include <gkyl_lua_utils.h>
#include <gkyl_mat.h>
#include <gkyl_mat_triples.h>
#include <gkyl_math.h>
#include <gkyl_mhd_src.h>
#include <gkyl_mom_bcorr_lbo_gyrokinetic.h>
#include <gkyl_mom_bcorr_lbo_pkpm.h>
#include <gkyl_mom_bcorr_lbo_vlasov.h>
#include <gkyl_mom_calc.h>
#include <gkyl_mom_calc_bcorr.h>
#include <gkyl_mom_canonical_pb.h>
#include <gkyl_mom_gyrokinetic.h>
#include <gkyl_mom_pkpm.h>
#include <gkyl_mom_type.h>
#include <gkyl_mom_vlasov.h>
#include <gkyl_mom_vlasov_sr.h>
#include <gkyl_moment_braginskii.h>
#include <gkyl_moment_em_coupling.h>
#include <gkyl_moment_prim_iso_euler.h>
#include <gkyl_moment_prim_mhd.h>
#include <gkyl_moment_prim_sr_euler.h>
#include <gkyl_mp_scheme.h>
#include <gkyl_mpi_comm.h>
#include <gkyl_nccl_comm.h>
#include <gkyl_null_comm.h>
#include <gkyl_null_pool.h>
#include <gkyl_prim_bgk_cross_calc.h>
#include <gkyl_prim_cross_m0deltas.h>
#include <gkyl_prim_lbo_calc.h>
#include <gkyl_prim_lbo_cross_calc.h>
#include <gkyl_prim_lbo_gyrokinetic.h>
#include <gkyl_prim_lbo_pkpm.h>
#include <gkyl_prim_lbo_type.h>
#include <gkyl_prim_lbo_vlasov.h>
#include <gkyl_proj_bimaxwellian_on_basis.h>
#include <gkyl_proj_maxwellian_on_basis.h>
#include <gkyl_proj_on_basis.h>
#include <gkyl_proj_powsqrt_on_basis.h>
#include <gkyl_range.h>
#include <gkyl_rect_decomp.h>
#include <gkyl_rect_grid.h>
#include <gkyl_ref_count.h>
#include <gkyl_source_utils.h>
#include <gkyl_sources_explicit.h>
#include <gkyl_sources_implicit.h>
#include <gkyl_spitzer_coll_freq.h>
#include <gkyl_superlu.h>
#include <gkyl_superlu_ops.h>
#include <gkyl_ten_moment_grad_closure.h>
#include <gkyl_thread_pool.h>
#include <gkyl_util.h>
#include <gkyl_vargm.h>
#include <gkyl_vlasov_lte_correct.h>
#include <gkyl_vlasov_lte_moments.h>
#include <gkyl_vlasov_lte_proj_on_basis.h>
#include <gkyl_wave_geom.h>
#include <gkyl_wave_prop.h>
#include <gkyl_wv_advect.h>
#include <gkyl_wv_apply_bc.h>
#include <gkyl_wv_burgers.h>
#include <gkyl_wv_coldfluid.h>
#include <gkyl_wv_eqn.h>
#include <gkyl_wv_euler.h>
#include <gkyl_wv_euler_mixture.h>
#include <gkyl_wv_gr_euler.h>
#include <gkyl_wv_gr_euler_tetrad.h>
#include <gkyl_wv_gr_maxwell.h>
#include <gkyl_wv_gr_maxwell_tetrad.h>
#include <gkyl_wv_gr_medium.h>
#include <gkyl_wv_gr_ultra_rel_euler.h>
#include <gkyl_wv_gr_ultra_rel_euler_tetrad.h>
#include <gkyl_wv_iso_euler.h>
#include <gkyl_wv_iso_euler_mixture.h>
#include <gkyl_wv_maxwell.h>
#include <gkyl_wv_mhd.h>
#include <gkyl_wv_reactive_euler.h>
#include <gkyl_wv_sr_euler.h>
#include <gkyl_wv_ten_moment.h>
#include <gkyl_app.h>
#include <gkyl_moment.h>
#include <gkyl_pkpm.h>
#include <gkyl_pkpm_lw.h>
#include <gkyl_vlasov.h>
#include <gkyl_vlasov_lw.h>
#include <gkyl_zero_lw.h>

#ifdef __cplusplus
}
#endif
